### ISSUE TITLE
服务器信息下没有返回服务器位置和IP信息

### ISSUE THREAD

**Issue by SimonGino** [wikihost-opensource/als#35]
BUG 简短描述

# 环境
Debian11 &docker version 23.0.1

使用的镜像版本 (`docker ps | grep als`):版本好像无返回值

# 现象
预期返回:
```
服务器信息正确返回服务器位置和IP信息
```
实际返回:
```
服务器信息下没有返回服务器位置和IP信息，详情见图片


```
![Snipaste_2023-03-24_14-59-45](https://user-images.githubusercontent.com/68073491/227448423-24af215a-95f7-490b-aa6a-b58f01304fb2.png)

**Comment by samlm0** [comment]
查看一下 docker logs `(容器ID)`

**Comment by SimonGino** [comment]
下面是我根据命令找到的日志文件：
[2023-03-24 06:49:55] Application is starting...
[2023-03-24 06:49:55] Working with nginx config...
[2023-03-24 06:49:55] Working with speedtest static file(s)...
[2023-03-24 06:49:55] Creating speedtest file with size: 1MB ...
[2023-03-24 06:49:55] Creating speedtest file with size: 10MB ...
[2023-03-24 06:49:55] Creating speedtest file with size: 100MB ...
[2023-03-24 06:49:55] Creating speedtest file with size: 1GB ...

===================================================================
 [FATAL ERROR]: all coroutines (count: 2) are asleep - deadlock!
===================================================================

 [Coroutine-2]
--------------------------------------------------------------------
#0 /app/components/05-websocket_server.php(30): Swoole\Coroutine\Http\Server->start()
#1 [internal function]: {closure}()


 [Coroutine-1]
--------------------------------------------------------------------
#0 /app/components/01-fake_file_server.php(53): Swoole\Coroutine\Http\Server->start()
#1 [internal function]: {closure}()

[2023-03-24 06:50:02] INFO: Waiting IP Database online...
[2023-03-24 06:50:03] INFO: Waiting IP Database online...
[2023-03-24 06:50:04] Uncompressing IP Database...
[2023-03-24 06:50:04] INFO: Waiting IP Database online...
[2023-03-24 06:50:05] INFO: Waiting IP Database online...
[2023-03-24 06:50:06] Process exited - PID: 14
[2023-03-24 06:50:06] Uncompressing IP Database...Done
[2023-03-24 06:50:06] ERROR: Failed to get public ipv6

**Comment by samlm0** [comment]
问题已经在 #36 中修复, 如果依旧没有办法获取到 IP 信息。

检查主机到 ifconfig.co 的链接
